name: Continuous Integration (CI)

on:
  push:
    branches:
      - master  # Workflow akan berjalan saat ada push ke branch master
  pull_request:
    branches:
      - master  # Workflow akan berjalan saat ada pull request ke branch master

jobs:
  build:
    runs-on: ubuntu-latest  # Menjalankan CI di environment Ubuntu

    steps:
      # Checkout repository dari GitHub
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Versi Node.js yang ingin digunakan

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Menjalankan semua test
      - name: Run tests
        run: npm test  # Menjalankan perintah test yang sudah ada di package.json